# -*- coding: utf-8 -*-
"""
/***************************************************************************
 whisp_analysis
                                 A QGIS plugin
 This plugin analyzes your geometries for deforestation risk through the OpenForis Whisp API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-27
        copyright            : (C) 2025 by Jonas Spekker/FAO
        email                : j.spkr92@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load whisp_analysis class from file whisp_analysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .whisp_analysis import whisp_analysis
    return whisp_analysis(iface)
